# Версия
version: '3'

services:

  pv121azure.storage.minio:
    container_name: pv121java.storage.minio
    image: minio/minio:latest
    command: server --console-address :9001 /data
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./volumes/minio:/data
    expose:
      - "9000"
      - "9001"
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password