# Версия
version: '3'

services:

  # Внутри этой машинки будет работать код на php
  # например laravel - RESTful API
  api.php:
    build: ./backend/api_php

  # Внутри этой машинки будут постоянные соединения
  # https://socket.io/docs/v4/redis-adapter/
  # мы реализуем вот такой тип соединения
  api.node:
    build: ./backend/api_node

  # SQL база данных
  db.mysql:
    image: mysql
    ports:
      - "3306:3306"
    env_file: # Мне нужно сообщить - какие настройки использовать
      - .env
    environment: # Плохой вариант - описать переменные прямо тут
      - SERVER_NAME=db.mySql

  # Добавим утилиту для удобства работы с базой и дадим ей порт
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db.mysql

  # InMemory DB база данных
  db.redis:
    image: redis

# Тип доступа в сеть
networks:
  itsteppv121azure:
    driver: bridge
