# Версия
version: '3'

services:

  pv121azure.front.public:
    build: frontend/public

  pv121azure.storage.minio:
    container_name: pv121azure.storage.minio
    image: minio/minio:latest
    command: server --console-address :9001 /data
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./volumes/minio:/data
    expose:
      - "9000"
      - "9001"
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password

  pv121azure.api.laravel:
    build: backend/api_laravel
    # Удобно вести разработку - поскольку данные (и файлы) из главной машины сразу попадают в контейнер
    volumes:
      - ./backend/api_laravel/src:/app
    environment:
      - SERVER_NAME=api_laravel

  pv121azure.api.node:
    build: backend/api_node
    environment:
      - SERVER_NAME=api_node


  pv121azure.api.hiload.jonny:
    build: backend/api_node
    environment:
      - SERVER_NAME=api.Jonny

  pv121azure.api.hiload.sunny:
    build: backend/api_node
    environment:
      - SERVER_NAME=api.Sunny

  # Nginx
  # Этот микросервис принимает запросы от пользователя
  # а уже внутри решает - куда - к какому микросвервису
  # отправить его на обработку
  pv121azure.nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - pv121azure.api.node
      - pv121azure.api.laravel
      - pv121azure.api.hiload.jonny
      - pv121azure.api.hiload.sunny
      - pv121azure.front.public

  # SQL база данных
  pv121azure.db.mysql:
    image: mysql
    ports:
      - "3306:3306"
    volumes: # Для сохранения данных я смонтирую папку
      - ./volumes/mysql:/var/lib/mysql
    env_file: # Мне нужно сообщить - какие настройки использовать
      - .env
    environment: # Плохой вариант - описать переменные прямо тут
      - SERVER_NAME=db.mySql

  # Добавим утилиту для удобства работы с базой и дадим ей порт
  pv121azure.phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=pv121azure.db.mysql

  # InMemory DB база данных
  pv121azure.db.redis:
    image: redis


# Тип доступа в сеть
#networks:
#  itsteppv121azure:
#    driver: bridge
